version: "3.9"

services:
    api:
        build: 
          context: .
          dockerfile: chat-server/Dockerfile
        ports:
            - "5000:80"
    app:
        build: 
            context: .
            dockerfile: chat-app/Dockerfile
        ports:
            - "4200:80"